//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace QLTKKH.securities_infoservice {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="_SECURITIES_INFOWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class _SECURITIES_INFOWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ThemSECURITIES_INFOOperationCompleted;
        
        private System.Threading.SendOrPostCallback XoaSECURITIES_INFOOperationCompleted;
        
        private System.Threading.SendOrPostCallback TinhMaMaxOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public _SECURITIES_INFOWebService() {
            this.Url = global::QLTKKH.Properties.Settings.Default.QLTKKH_securities_infoservice__SECURITIES_INFOWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ThemSECURITIES_INFOCompletedEventHandler ThemSECURITIES_INFOCompleted;
        
        /// <remarks/>
        public event XoaSECURITIES_INFOCompletedEventHandler XoaSECURITIES_INFOCompleted;
        
        /// <remarks/>
        public event TinhMaMaxCompletedEventHandler TinhMaMaxCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemSECURITIES_INFO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ThemSECURITIES_INFO(string codeid, string symbol, long floorprice, long celingprice, long basicprice, double mrratiorate, string company) {
            this.Invoke("ThemSECURITIES_INFO", new object[] {
                        codeid,
                        symbol,
                        floorprice,
                        celingprice,
                        basicprice,
                        mrratiorate,
                        company});
        }
        
        /// <remarks/>
        public void ThemSECURITIES_INFOAsync(string codeid, string symbol, long floorprice, long celingprice, long basicprice, double mrratiorate, string company) {
            this.ThemSECURITIES_INFOAsync(codeid, symbol, floorprice, celingprice, basicprice, mrratiorate, company, null);
        }
        
        /// <remarks/>
        public void ThemSECURITIES_INFOAsync(string codeid, string symbol, long floorprice, long celingprice, long basicprice, double mrratiorate, string company, object userState) {
            if ((this.ThemSECURITIES_INFOOperationCompleted == null)) {
                this.ThemSECURITIES_INFOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemSECURITIES_INFOOperationCompleted);
            }
            this.InvokeAsync("ThemSECURITIES_INFO", new object[] {
                        codeid,
                        symbol,
                        floorprice,
                        celingprice,
                        basicprice,
                        mrratiorate,
                        company}, this.ThemSECURITIES_INFOOperationCompleted, userState);
        }
        
        private void OnThemSECURITIES_INFOOperationCompleted(object arg) {
            if ((this.ThemSECURITIES_INFOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemSECURITIES_INFOCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XoaSECURITIES_INFO", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void XoaSECURITIES_INFO(string codeid) {
            this.Invoke("XoaSECURITIES_INFO", new object[] {
                        codeid});
        }
        
        /// <remarks/>
        public void XoaSECURITIES_INFOAsync(string codeid) {
            this.XoaSECURITIES_INFOAsync(codeid, null);
        }
        
        /// <remarks/>
        public void XoaSECURITIES_INFOAsync(string codeid, object userState) {
            if ((this.XoaSECURITIES_INFOOperationCompleted == null)) {
                this.XoaSECURITIES_INFOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXoaSECURITIES_INFOOperationCompleted);
            }
            this.InvokeAsync("XoaSECURITIES_INFO", new object[] {
                        codeid}, this.XoaSECURITIES_INFOOperationCompleted, userState);
        }
        
        private void OnXoaSECURITIES_INFOOperationCompleted(object arg) {
            if ((this.XoaSECURITIES_INFOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XoaSECURITIES_INFOCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TinhMaMax", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TinhMaMax(string column1, string table1) {
            object[] results = this.Invoke("TinhMaMax", new object[] {
                        column1,
                        table1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TinhMaMaxAsync(string column1, string table1) {
            this.TinhMaMaxAsync(column1, table1, null);
        }
        
        /// <remarks/>
        public void TinhMaMaxAsync(string column1, string table1, object userState) {
            if ((this.TinhMaMaxOperationCompleted == null)) {
                this.TinhMaMaxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTinhMaMaxOperationCompleted);
            }
            this.InvokeAsync("TinhMaMax", new object[] {
                        column1,
                        table1}, this.TinhMaMaxOperationCompleted, userState);
        }
        
        private void OnTinhMaMaxOperationCompleted(object arg) {
            if ((this.TinhMaMaxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TinhMaMaxCompleted(this, new TinhMaMaxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ThemSECURITIES_INFOCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void XoaSECURITIES_INFOCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TinhMaMaxCompletedEventHandler(object sender, TinhMaMaxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TinhMaMaxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TinhMaMaxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591