//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace QLTKKH.lnmastservice {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="_LNMASTWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class _LNMASTWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ThemLNMASTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public _LNMASTWebService() {
            this.Url = global::QLTKKH.Properties.Settings.Default.QLTKKH_lnmastservice__LNMASTWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ThemLNMASTCompletedEventHandler ThemLNMASTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemLNMAST", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ThemLNMAST(string acctno, long prinnml, long intdue, long intnmlacr, long rate1, long rate2, long rate3, System.DateTime lastdate, System.DateTime opndate, System.DateTime rlsdate) {
            this.Invoke("ThemLNMAST", new object[] {
                        acctno,
                        prinnml,
                        intdue,
                        intnmlacr,
                        rate1,
                        rate2,
                        rate3,
                        lastdate,
                        opndate,
                        rlsdate});
        }
        
        /// <remarks/>
        public void ThemLNMASTAsync(string acctno, long prinnml, long intdue, long intnmlacr, long rate1, long rate2, long rate3, System.DateTime lastdate, System.DateTime opndate, System.DateTime rlsdate) {
            this.ThemLNMASTAsync(acctno, prinnml, intdue, intnmlacr, rate1, rate2, rate3, lastdate, opndate, rlsdate, null);
        }
        
        /// <remarks/>
        public void ThemLNMASTAsync(string acctno, long prinnml, long intdue, long intnmlacr, long rate1, long rate2, long rate3, System.DateTime lastdate, System.DateTime opndate, System.DateTime rlsdate, object userState) {
            if ((this.ThemLNMASTOperationCompleted == null)) {
                this.ThemLNMASTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemLNMASTOperationCompleted);
            }
            this.InvokeAsync("ThemLNMAST", new object[] {
                        acctno,
                        prinnml,
                        intdue,
                        intnmlacr,
                        rate1,
                        rate2,
                        rate3,
                        lastdate,
                        opndate,
                        rlsdate}, this.ThemLNMASTOperationCompleted, userState);
        }
        
        private void OnThemLNMASTOperationCompleted(object arg) {
            if ((this.ThemLNMASTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemLNMASTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ThemLNMASTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591