//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace QLTKKH.afmastservice {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="_AFMASTWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class _AFMASTWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ThemAFMASTOperationCompleted;
        
        private System.Threading.SendOrPostCallback SuaAFMASTOperationCompleted;
        
        private System.Threading.SendOrPostCallback XoaAFMASTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public _AFMASTWebService() {
            this.Url = global::QLTKKH.Properties.Settings.Default.QLTKKH_cfmastservice1__AFMASTWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ThemAFMASTCompletedEventHandler ThemAFMASTCompleted;
        
        /// <remarks/>
        public event SuaAFMASTCompletedEventHandler SuaAFMASTCompleted;
        
        /// <remarks/>
        public event XoaAFMASTCompletedEventHandler XoaAFMASTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemAFMAST", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ThemAFMAST(string custid, string acctno, string martype, long mrcrlimitmax, string afacctno, long balance, long cidepofeeacr, long depofeeamt, System.DateTime lastchange) {
            this.Invoke("ThemAFMAST", new object[] {
                        custid,
                        acctno,
                        martype,
                        mrcrlimitmax,
                        afacctno,
                        balance,
                        cidepofeeacr,
                        depofeeamt,
                        lastchange});
        }
        
        /// <remarks/>
        public void ThemAFMASTAsync(string custid, string acctno, string martype, long mrcrlimitmax, string afacctno, long balance, long cidepofeeacr, long depofeeamt, System.DateTime lastchange) {
            this.ThemAFMASTAsync(custid, acctno, martype, mrcrlimitmax, afacctno, balance, cidepofeeacr, depofeeamt, lastchange, null);
        }
        
        /// <remarks/>
        public void ThemAFMASTAsync(string custid, string acctno, string martype, long mrcrlimitmax, string afacctno, long balance, long cidepofeeacr, long depofeeamt, System.DateTime lastchange, object userState) {
            if ((this.ThemAFMASTOperationCompleted == null)) {
                this.ThemAFMASTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemAFMASTOperationCompleted);
            }
            this.InvokeAsync("ThemAFMAST", new object[] {
                        custid,
                        acctno,
                        martype,
                        mrcrlimitmax,
                        afacctno,
                        balance,
                        cidepofeeacr,
                        depofeeamt,
                        lastchange}, this.ThemAFMASTOperationCompleted, userState);
        }
        
        private void OnThemAFMASTOperationCompleted(object arg) {
            if ((this.ThemAFMASTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemAFMASTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuaAFMAST", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SuaAFMAST(string custid, string acctno, string martype, long mrcrlimitmax) {
            this.Invoke("SuaAFMAST", new object[] {
                        custid,
                        acctno,
                        martype,
                        mrcrlimitmax});
        }
        
        /// <remarks/>
        public void SuaAFMASTAsync(string custid, string acctno, string martype, long mrcrlimitmax) {
            this.SuaAFMASTAsync(custid, acctno, martype, mrcrlimitmax, null);
        }
        
        /// <remarks/>
        public void SuaAFMASTAsync(string custid, string acctno, string martype, long mrcrlimitmax, object userState) {
            if ((this.SuaAFMASTOperationCompleted == null)) {
                this.SuaAFMASTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuaAFMASTOperationCompleted);
            }
            this.InvokeAsync("SuaAFMAST", new object[] {
                        custid,
                        acctno,
                        martype,
                        mrcrlimitmax}, this.SuaAFMASTOperationCompleted, userState);
        }
        
        private void OnSuaAFMASTOperationCompleted(object arg) {
            if ((this.SuaAFMASTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuaAFMASTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XoaAFMAST", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void XoaAFMAST(string custid, string acctno) {
            this.Invoke("XoaAFMAST", new object[] {
                        custid,
                        acctno});
        }
        
        /// <remarks/>
        public void XoaAFMASTAsync(string custid, string acctno) {
            this.XoaAFMASTAsync(custid, acctno, null);
        }
        
        /// <remarks/>
        public void XoaAFMASTAsync(string custid, string acctno, object userState) {
            if ((this.XoaAFMASTOperationCompleted == null)) {
                this.XoaAFMASTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXoaAFMASTOperationCompleted);
            }
            this.InvokeAsync("XoaAFMAST", new object[] {
                        custid,
                        acctno}, this.XoaAFMASTOperationCompleted, userState);
        }
        
        private void OnXoaAFMASTOperationCompleted(object arg) {
            if ((this.XoaAFMASTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XoaAFMASTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ThemAFMASTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SuaAFMASTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void XoaAFMASTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591